# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# source '/Users/jingbin/.cocoapods/repos/CocoaPods/Specs'

# source 'https://gitee.com/mirrors/CocoaPods-Specs/tree/master/Specs'

target 'quote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.5.0'
  pod 'MagazineLayout'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'SnapKit', '~> 5.6.0'
  pod 'MJRefresh' #, '3.2.2'
# platform :ios, '10.0'
#  pod 'SDWebImage'
  pod 'SDWebImage', '~> 5.0'
  pod 'RealmSwift', '~>10'
#pod 'SDWebImageWebPCoder'

  pod 'AFNetworking', '~> 4.0'

#  pod 'YYModel', :path => './Local/YYModel'
  # Pods for quote

end
